---
title: Ajouter des icônes Google
hero_image: images/banner.png
description: Ajouter des icônes Google
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Ajouter des icônes Google
